// Code generated by protoc-gen-go. DO NOT EDIT.
// source: transaction.proto

package XXXX

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Transaction struct {
	From                 string   `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To                   string   `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Amount               uint64   `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Uid                  uint64   `protobuf:"varint,4,opt,name=uid,proto3" json:"uid,omitempty"`
	Version              uint64   `protobuf:"varint,5,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Transaction) Reset()         { *m = Transaction{} }
func (m *Transaction) String() string { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()    {}
func (*Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{0}
}

func (m *Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction.Unmarshal(m, b)
}
func (m *Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction.Marshal(b, m, deterministic)
}
func (m *Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction.Merge(m, src)
}
func (m *Transaction) XXX_Size() int {
	return xxx_messageInfo_Transaction.Size(m)
}
func (m *Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction proto.InternalMessageInfo

func (m *Transaction) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *Transaction) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *Transaction) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *Transaction) GetUid() uint64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *Transaction) GetVersion() uint64 {
	if m != nil {
		return m.Version
	}
	return 0
}

type TransactionsResult struct {
	Uid                  uint64   `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Ret                  int32    `protobuf:"varint,2,opt,name=ret,proto3" json:"ret,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransactionsResult) Reset()         { *m = TransactionsResult{} }
func (m *TransactionsResult) String() string { return proto.CompactTextString(m) }
func (*TransactionsResult) ProtoMessage()    {}
func (*TransactionsResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{1}
}

func (m *TransactionsResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionsResult.Unmarshal(m, b)
}
func (m *TransactionsResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionsResult.Marshal(b, m, deterministic)
}
func (m *TransactionsResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionsResult.Merge(m, src)
}
func (m *TransactionsResult) XXX_Size() int {
	return xxx_messageInfo_TransactionsResult.Size(m)
}
func (m *TransactionsResult) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionsResult.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionsResult proto.InternalMessageInfo

func (m *TransactionsResult) GetUid() uint64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *TransactionsResult) GetRet() int32 {
	if m != nil {
		return m.Ret
	}
	return 0
}

type TransactionsRequest struct {
	Transactions         []*Transaction `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *TransactionsRequest) Reset()         { *m = TransactionsRequest{} }
func (m *TransactionsRequest) String() string { return proto.CompactTextString(m) }
func (*TransactionsRequest) ProtoMessage()    {}
func (*TransactionsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{2}
}

func (m *TransactionsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionsRequest.Unmarshal(m, b)
}
func (m *TransactionsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionsRequest.Marshal(b, m, deterministic)
}
func (m *TransactionsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionsRequest.Merge(m, src)
}
func (m *TransactionsRequest) XXX_Size() int {
	return xxx_messageInfo_TransactionsRequest.Size(m)
}
func (m *TransactionsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionsRequest proto.InternalMessageInfo

func (m *TransactionsRequest) GetTransactions() []*Transaction {
	if m != nil {
		return m.Transactions
	}
	return nil
}

type TransactionsResponse struct {
	Result               []*TransactionsResult `protobuf:"bytes,1,rep,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *TransactionsResponse) Reset()         { *m = TransactionsResponse{} }
func (m *TransactionsResponse) String() string { return proto.CompactTextString(m) }
func (*TransactionsResponse) ProtoMessage()    {}
func (*TransactionsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{3}
}

func (m *TransactionsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionsResponse.Unmarshal(m, b)
}
func (m *TransactionsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionsResponse.Marshal(b, m, deterministic)
}
func (m *TransactionsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionsResponse.Merge(m, src)
}
func (m *TransactionsResponse) XXX_Size() int {
	return xxx_messageInfo_TransactionsResponse.Size(m)
}
func (m *TransactionsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionsResponse proto.InternalMessageInfo

func (m *TransactionsResponse) GetResult() []*TransactionsResult {
	if m != nil {
		return m.Result
	}
	return nil
}

type TransactionQuery struct {
	Uids                 []uint64 `protobuf:"varint,1,rep,packed,name=uids,proto3" json:"uids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransactionQuery) Reset()         { *m = TransactionQuery{} }
func (m *TransactionQuery) String() string { return proto.CompactTextString(m) }
func (*TransactionQuery) ProtoMessage()    {}
func (*TransactionQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{4}
}

func (m *TransactionQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionQuery.Unmarshal(m, b)
}
func (m *TransactionQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionQuery.Marshal(b, m, deterministic)
}
func (m *TransactionQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionQuery.Merge(m, src)
}
func (m *TransactionQuery) XXX_Size() int {
	return xxx_messageInfo_TransactionQuery.Size(m)
}
func (m *TransactionQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionQuery.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionQuery proto.InternalMessageInfo

func (m *TransactionQuery) GetUids() []uint64 {
	if m != nil {
		return m.Uids
	}
	return nil
}

func init() {
	proto.RegisterType((*Transaction)(nil), "XXXX.Transaction")
	proto.RegisterType((*TransactionsResult)(nil), "XXXX.TransactionsResult")
	proto.RegisterType((*TransactionsRequest)(nil), "XXXX.TransactionsRequest")
	proto.RegisterType((*TransactionsResponse)(nil), "XXXX.TransactionsResponse")
	proto.RegisterType((*TransactionQuery)(nil), "XXXX.TransactionQuery")
}

func init() { proto.RegisterFile("transaction.proto", fileDescriptor_2cc4e03d2c28c490) }

var fileDescriptor_2cc4e03d2c28c490 = []byte{
	// 253 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x91, 0xbb, 0x4b, 0xc4, 0x40,
	0x10, 0xc6, 0xd9, 0xbc, 0xd4, 0x39, 0x91, 0x38, 0x8a, 0xac, 0x5d, 0xd8, 0x42, 0x52, 0x45, 0x54,
	0x10, 0xc1, 0xce, 0xce, 0xc2, 0xc2, 0xc5, 0xca, 0x2e, 0x67, 0x56, 0x08, 0x78, 0x3b, 0xe7, 0x3e,
	0x04, 0xff, 0x7b, 0xc9, 0x18, 0xbd, 0x3d, 0xed, 0xbe, 0x79, 0xfd, 0xe6, 0x9b, 0x5d, 0x38, 0x0c,
	0xae, 0xb7, 0xbe, 0x7f, 0x09, 0x23, 0xd9, 0x6e, 0xed, 0x28, 0x10, 0x96, 0xce, 0xf8, 0x61, 0xa9,
	0x22, 0x2c, 0x9e, 0x36, 0x35, 0x44, 0x28, 0x5e, 0x1d, 0xad, 0xa4, 0x68, 0x44, 0xbb, 0xa7, 0x59,
	0xe3, 0x01, 0x64, 0x81, 0x64, 0xc6, 0x99, 0x2c, 0x10, 0x9e, 0x40, 0xd5, 0xaf, 0x28, 0xda, 0x20,
	0xf3, 0x46, 0xb4, 0x85, 0x9e, 0x23, 0xac, 0x21, 0x8f, 0xe3, 0x20, 0x0b, 0x4e, 0x4e, 0x12, 0x25,
	0xec, 0x7c, 0x18, 0xe7, 0x47, 0xb2, 0xb2, 0xe4, 0xec, 0x4f, 0xa8, 0x6e, 0x00, 0x93, 0xb5, 0x5e,
	0x1b, 0x1f, 0xdf, 0x7e, 0x09, 0x62, 0x43, 0xa8, 0x21, 0x77, 0x26, 0xf0, 0xf2, 0x52, 0x4f, 0x52,
	0x3d, 0xc0, 0xd1, 0xf6, 0xe4, 0x7b, 0x34, 0x3e, 0xe0, 0x35, 0xec, 0x27, 0x37, 0x7a, 0x29, 0x9a,
	0xbc, 0x5d, 0x5c, 0x62, 0xc7, 0x57, 0x76, 0xc9, 0x84, 0xde, 0xea, 0x53, 0xf7, 0x70, 0xfc, 0xc7,
	0xc8, 0x9a, 0xac, 0x37, 0x78, 0x01, 0x95, 0x63, 0x53, 0x33, 0xe9, 0xf4, 0x3f, 0x69, 0x76, 0xad,
	0xe7, 0x46, 0x75, 0x06, 0x75, 0x52, 0x7d, 0x8c, 0xc6, 0x7d, 0x4e, 0xef, 0x19, 0xc7, 0xe1, 0xdb,
	0x4e, 0xa1, 0x59, 0xdf, 0xc1, 0xf3, 0x6e, 0x77, 0x7e, 0xcb, 0xb8, 0x65, 0xc5, 0x9f, 0x71, 0xf5,
	0x15, 0x00, 0x00, 0xff, 0xff, 0x30, 0xd1, 0x67, 0x29, 0xa1, 0x01, 0x00, 0x00,
}
